server:
  port: 8080
spring:
  application:
    name: todo-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
  flyway:
    enabled: true
    locations: classpath:db/migration
